### DISCUSSION TITLE
Consider using linters / autoformatters

### DISCUSSION THREAD

**Discussion by panjacek** [time4tea/gopro-dashboard-overlay#207] [General]
I was working today with app and I've realized is not auto-formatted and any run of isort / black / ruff will return plenty of "issues" some real while others are style things.

I think it would be worth to consider adopting auto formatting.

All rules can be described in pyproject.toml (including pytest.ini stuff) e.g.
```toml
[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 120

[tool.ruff]
line-length = 120

[tool.coverage.run]
source = ["sc4_mapper"]

[tool.pytest.ini_options]
addopts = "--cov=sc4_mapper --cov-report term-missing"
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)s][%(filename)s:%(lineno)s]%(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
```
